// components/green-credits/CreditTypesShowcase.js
'use client';
import { useState } from 'react';

const GREEN_CREDIT_TYPES = [
  {
    id: 1,
    name: "Solar Energy Credits",
    icon: "☀️",
    description: "Generated from solar power projects reducing fossil fuel dependency",
    benefits: ["CO2 Reduction", "Renewable Energy", "Grid Stability"],
    projects: ["Solar Farms", "Rooftop Solar", "Solar Parks"],
    priceRange: "$75-95",
    demand: "High"
  },
  {
    id: 2,
    name: "Wind Energy Credits",
    icon: "💨",
    description: "From wind farms harnessing wind power for clean electricity",
    benefits: ["Zero Emissions", "Land Preservation", "Water Conservation"],
    projects: ["Onshore Wind", "Offshore Wind", "Wind Turbines"],
    priceRange: "$70-90",
    demand: "High"
  },
  {
    id: 3,
    name: "Hydroelectric Credits",
    icon: "💧",
    description: "Generated by hydroelectric plants using water flow for power",
    benefits: ["Renewable", "Flood Control", "Water Management"],
    projects: ["Dams", "Run-of-river", "Pumped Storage"],
    priceRange: "$65-85",
    demand: "Medium"
  },
  {
    id: 4,
    name: "Biomass Energy Credits",
    icon: "🌿",
    description: "From organic material conversion to energy",
    benefits: ["Waste Reduction", "Carbon Neutral", "Rural Development"],
    projects: ["Biogas Plants", "Biofuel", "Agricultural Waste"],
    priceRange: "$60-80",
    demand: "Medium"
  },
  {
    id: 5,
    name: "Carbon Sequestration",
    icon: "🌳",
    description: "Credits for capturing and storing atmospheric carbon",
    benefits: ["Climate Mitigation", "Biodiversity", "Soil Health"],
    projects: ["Reforestation", "Soil Carbon", "Direct Air Capture"],
    priceRange: "$85-110",
    demand: "Very High"
  },
  {
    id: 6,
    name: "Water Conservation",
    icon: "🚰",
    description: "Credits for efficient water use and conservation projects",
    benefits: ["Water Security", "Ecosystem Protection", "Sustainable Agriculture"],
    projects: ["Water Harvesting", "Efficient Irrigation", "Watershed Management"],
    priceRange: "$70-90",
    demand: "Growing"
  },
  {
    id: 7,
    name: "Biodiversity Credits",
    icon: "🦋",
    description: "For projects protecting and enhancing biodiversity",
    benefits: ["Habitat Protection", "Species Conservation", "Ecosystem Services"],
    projects: ["Wildlife Corridors", "Habitat Restoration", "Protected Areas"],
    priceRange: "$80-100",
    demand: "Medium"
  },
  {
    id: 8,
    name: "Waste Management",
    icon: "♻️",
    description: "Credits from waste reduction and recycling initiatives",
    benefits: ["Pollution Reduction", "Resource Efficiency", "Circular Economy"],
    projects: ["Recycling", "Composting", "Waste-to-Energy"],
    priceRange: "$55-75",
    demand: "Medium"
  }
];

export default function CreditTypesShowcase() {
  const [selectedType, setSelectedType] = useState(GREEN_CREDIT_TYPES[0]);

  return (
    <div className="max-w-7xl mx-auto py-12 px-4">
      <div className="text-center mb-12">
        <h2 className="text-4xl font-bold text-green-900 mb-4">
          Green Credit Types
        </h2>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Discover the diverse range of environmental credits available for trading on our platform. 
          Each credit represents verified environmental benefits.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        {/* Sidebar - Credit Type List */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 sticky top-4">
            <h3 className="font-semibold text-gray-800 mb-4">Credit Categories</h3>
            <div className="space-y-2">
              {GREEN_CREDIT_TYPES.map((type) => (
                <button
                  key={type.id}
                  onClick={() => setSelectedType(type)}
                  className={`w-full text-left p-3 rounded-lg transition-all ${
                    selectedType.id === type.id
                      ? 'bg-green-100 border border-green-300 text-green-800'
                      : 'bg-gray-50 hover:bg-gray-100 text-gray-700'
                  }`}
                >
                  <div className="flex items-center space-x-3">
                    <span className="text-2xl">{type.icon}</span>
                    <div>
                      <div className="font-medium text-sm">{type.name}</div>
                      <div className="text-xs text-gray-500">{type.demand} Demand</div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Main Content - Selected Type Details */}
        <div className="lg:col-span-3">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
            {/* Header */}
            <div className="bg-gradient-to-r from-green-600 to-emerald-700 p-6 text-white">
              <div className="flex items-center space-x-4">
                <span className="text-4xl">{selectedType.icon}</span>
                <div>
                  <h3 className="text-2xl font-bold">{selectedType.name}</h3>
                  <p className="text-green-100">{selectedType.description}</p>
                </div>
              </div>
            </div>

            {/* Details */}
            <div className="p-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Left Column */}
                <div className="space-y-6">
                  <div>
                    <h4 className="font-semibold text-gray-800 mb-3">Environmental Benefits</h4>
                    <div className="space-y-2">
                      {selectedType.benefits.map((benefit, index) => (
                        <div key={index} className="flex items-center space-x-2">
                          <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                          <span className="text-gray-700">{benefit}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <h4 className="font-semibold text-gray-800 mb-3">Project Types</h4>
                    <div className="flex flex-wrap gap-2">
                      {selectedType.projects.map((project, index) => (
                        <span
                          key={index}
                          className="bg-green-50 text-green-700 px-3 py-1 rounded-full text-sm"
                        >
                          {project}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>

                {/* Right Column */}
                <div className="space-y-6">
                  <div className="bg-gray-50 rounded-lg p-4">
                    <h4 className="font-semibold text-gray-800 mb-2">Market Information</h4>
                    <div className="space-y-3">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Price Range:</span>
                        <span className="font-bold text-green-600">{selectedType.priceRange}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Market Demand:</span>
                        <span className={`font-bold ${
                          selectedType.demand === 'Very High' ? 'text-red-600' :
                          selectedType.demand === 'High' ? 'text-orange-600' :
                          selectedType.demand === 'Growing' ? 'text-green-600' : 'text-blue-600'
                        }`}>
                          {selectedType.demand}
                        </span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Verification:</span>
                        <span className="font-bold text-green-600">Required</span>
                      </div>
                    </div>
                  </div>

                  <div>
                    <h4 className="font-semibold text-gray-800 mb-3">Trading Volume</h4>
                    <div className="bg-gradient-to-r from-green-400 to-blue-500 h-3 rounded-full w-full"></div>
                    <div className="flex justify-between text-sm text-gray-600 mt-2">
                      <span>Low</span>
                      <span>High</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="mt-8 flex space-x-4">
                <button className="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 transition-colors font-semibold">
                  View Available Credits
                </button>
                <button className="border border-green-600 text-green-600 px-6 py-3 rounded-lg hover:bg-green-50 transition-colors font-semibold">
                  Learn About Verification
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}